
// This file has been generated by the GUI designer. Do not modify.
namespace SharpSimulator
{
	public partial class SimulatorWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.VBox MainBox;
		
		private global::Gtk.HButtonBox MainButtonBox;
		
		private global::Gtk.Frame MainFrame;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Label SimulationLabel;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TextView SimulationDebugLabel;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView EntityOverviewLabel;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SharpSimulator.SimulatorWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "SharpSimulator.SimulatorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SharpSimulator");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Container child SharpSimulator.SimulatorWindow.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.WidthRequest = 800;
			this.vpaned1.HeightRequest = 600;
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 546;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.MainBox = new global::Gtk.VBox ();
			this.MainBox.Name = "MainBox";
			this.MainBox.Spacing = 6;
			// Container child MainBox.Gtk.Box+BoxChild
			this.MainButtonBox = new global::Gtk.HButtonBox ();
			this.MainButtonBox.Name = "MainButtonBox";
			this.MainBox.Add (this.MainButtonBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.MainButtonBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child MainBox.Gtk.Box+BoxChild
			this.MainFrame = new global::Gtk.Frame ();
			this.MainFrame.Name = "MainFrame";
			this.MainFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child MainFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.MainFrame.Add (this.GtkAlignment);
			this.SimulationLabel = new global::Gtk.Label ();
			this.SimulationLabel.Name = "SimulationLabel";
			this.SimulationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulation");
			this.SimulationLabel.UseMarkup = true;
			this.MainFrame.LabelWidget = this.SimulationLabel;
			this.MainBox.Add (this.MainFrame);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.MainFrame]));
			w4.Position = 1;
			this.vpaned1.Add (this.MainBox);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.MainBox]));
			w5.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.SimulationDebugLabel = new global::Gtk.TextView ();
			this.SimulationDebugLabel.CanFocus = true;
			this.SimulationDebugLabel.Name = "SimulationDebugLabel";
			this.GtkScrolledWindow1.Add (this.SimulationDebugLabel);
			this.notebook1.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulator Debug");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.EntityOverviewLabel = new global::Gtk.TextView ();
			this.EntityOverviewLabel.CanFocus = true;
			this.EntityOverviewLabel.Name = "EntityOverviewLabel";
			this.GtkScrolledWindow.Add (this.EntityOverviewLabel);
			this.notebook1.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow]));
			w9.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Entity Overview");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label2);
			this.label2.ShowAll ();
			this.vpaned1.Add (this.notebook1);
			global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.notebook1]));
			w10.Resize = false;
			w10.Shrink = false;
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
