
// This file has been generated by the GUI designer. Do not modify.
namespace SharpSimulator
{
	public partial class SimulatorWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.VBox MainBox;
		
		private global::Gtk.HButtonBox MainButtonBox;
		
		private global::Gtk.Frame MainFrame;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.Alignment MainAlignement;
		
		private global::Gtk.Label SimulationLabel;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow SimulationDebugLabelContainer;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView EntityOverviewLabel;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TextView SimulationOverviewLabel;
		
		private global::Gtk.Label SimulationOverview;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SharpSimulator.SimulatorWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.WidthRequest = 800;
			this.HeightRequest = 600;
			this.Name = "SharpSimulator.SimulatorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SharpSimulator");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 800;
			this.DefaultHeight = 600;
			// Container child SharpSimulator.SimulatorWindow.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.WidthRequest = 800;
			this.vpaned1.HeightRequest = 600;
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 580;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.MainBox = new global::Gtk.VBox ();
			this.MainBox.Name = "MainBox";
			this.MainBox.Spacing = 6;
			// Container child MainBox.Gtk.Box+BoxChild
			this.MainButtonBox = new global::Gtk.HButtonBox ();
			this.MainButtonBox.Name = "MainButtonBox";
			this.MainBox.Add (this.MainButtonBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.MainButtonBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child MainBox.Gtk.Box+BoxChild
			this.MainFrame = new global::Gtk.Frame ();
			this.MainFrame.Name = "MainFrame";
			this.MainFrame.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child MainFrame.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.MainAlignement = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.MainAlignement.Name = "MainAlignement";
			this.MainAlignement.LeftPadding = ((uint)(12));
			w3.Add (this.MainAlignement);
			this.GtkScrolledWindow2.Add (w3);
			this.MainFrame.Add (this.GtkScrolledWindow2);
			this.SimulationLabel = new global::Gtk.Label ();
			this.SimulationLabel.Name = "SimulationLabel";
			this.SimulationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulation");
			this.SimulationLabel.UseMarkup = true;
			this.MainFrame.LabelWidget = this.SimulationLabel;
			this.MainBox.Add (this.MainFrame);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.MainFrame]));
			w7.Position = 1;
			this.vpaned1.Add (this.MainBox);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.MainBox]));
			w8.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.SimulationDebugLabelContainer = new global::Gtk.ScrolledWindow ();
			this.SimulationDebugLabelContainer.CanFocus = true;
			this.SimulationDebugLabelContainer.Name = "SimulationDebugLabelContainer";
			this.SimulationDebugLabelContainer.ShadowType = ((global::Gtk.ShadowType)(1));
			this.notebook1.Add (this.SimulationDebugLabelContainer);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulator Debug");
			this.notebook1.SetTabLabel (this.SimulationDebugLabelContainer, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.EntityOverviewLabel = new global::Gtk.TextView ();
			this.EntityOverviewLabel.CanFocus = true;
			this.EntityOverviewLabel.Name = "EntityOverviewLabel";
			this.GtkScrolledWindow.Add (this.EntityOverviewLabel);
			this.notebook1.Add (this.GtkScrolledWindow);
			global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow]));
			w11.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Entity Overview");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.SimulationOverviewLabel = new global::Gtk.TextView ();
			this.SimulationOverviewLabel.CanFocus = true;
			this.SimulationOverviewLabel.Name = "SimulationOverviewLabel";
			this.GtkScrolledWindow3.Add (this.SimulationOverviewLabel);
			this.notebook1.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow3]));
			w13.Position = 2;
			// Notebook tab
			this.SimulationOverview = new global::Gtk.Label ();
			this.SimulationOverview.Name = "SimulationOverview";
			this.SimulationOverview.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulation Overview");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow3, this.SimulationOverview);
			this.SimulationOverview.ShowAll ();
			this.vpaned1.Add (this.notebook1);
			global::Gtk.Paned.PanedChild w14 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.notebook1]));
			w14.Resize = false;
			w14.Shrink = false;
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
